services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.20.0
    command: ["--config", "/etc/jaeger/config.yaml"]
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP
    volumes:
      - ./jaeger/config.yaml:/etc/jaeger/config.yaml:ro
      - ./runs/jaeger:/var/lib/jaeger
